### ISSUE TITLE
Could not GET 'https://dl.bintray.com/umsdk/release/com/umeng/umsdk/apm/1.1.1/apm-1.1.1.pom'

### ISSUE THREAD

**Issue by OneHangH** [yz1311/rn-umeng-module#1]
![image](https://user-images.githubusercontent.com/31791685/119955335-8a581d80-bfd2-11eb-965f-9faab8b1b184.png)

https://dl.bintray.com/umsdk/release/com/umeng/umsdk/apm/1.1.1/apm-1.1.1.pom   yarn android时无法装上这个包，路径有问题，请问可以怎么解决

**Comment by yz1311** [comment]
你按照配置，在android/build.gradle里面加上umeng仓库地址没?

**Comment by OneHangH** [comment]
> 你按照配置，在android/build.gradle里面加上umeng仓库地址没?

加了的，这个域名https://dl.bintray.com 访问不到

**Comment by yz1311** [comment]
你标题上的这个地址，你是直接访问不到，还是访问报错？

**Comment by OneHangH** [comment]
> 你标题上的这个地址，你是直接访问不到，还是访问报错？
显示：Forbidden!
![image](https://user-images.githubusercontent.com/31791685/119956990-3fd7a080-bfd4-11eb-8f77-b1f3ff9f5aec.png)

**Comment by yz1311** [comment]
maven { url  'https://repo1.maven.org/maven2/'}


你将地址换成这个试下

**Comment by OneHangH** [comment]
> maven { url '[https://repo1.maven.org/maven2/'}](https://repo1.maven.org/maven2/'%7D)
> 
> 你将地址换成这个试下

替换完后将您的包下的 implementation 'com.umeng.umsdk:apm:1.1.1' 版本号改为1.2.0后就可以下载到资源了，
之后想问下您在andorid的 MainActivity 和MainApplication中需要分别引入哪些包？
![image](https://user-images.githubusercontent.com/31791685/119960903-0a34b680-bfd8-11eb-8490-f4564acffbf9.png)

**Comment by yz1311** [comment]
你用android studio打开android项目直接有ide提示引入的
MainApplication：
import com.umeng.commonsdk.UMConfigure;
import com.umeng.socialize.PlatformConfig;
import com.umeng.socialize.UMShareAPI;

MainActivity：
import com.reactlibrary.umeng.RNShareModule;
import com.umeng.analytics.MobclickAgent;
import com.umeng.socialize.UMShareAPI;

**Comment by OneHangH** [comment]
> 你用android studio打开android项目直接有ide提示引入的
> MainApplication：
> import com.umeng.commonsdk.UMConfigure;
> import com.umeng.socialize.PlatformConfig;
> import com.umeng.socialize.UMShareAPI;
> 
> MainActivity：
> import com.reactlibrary.umeng.RNShareModule;
> import com.umeng.analytics.MobclickAgent;
> import com.umeng.socialize.UMShareAPI;

好的，十分感谢
