### ISSUE TITLE
请问大佬有空升级umeng的sdk到最新版本吗？umeng的最新版本升级了合规的一些问题，不升级会有下架风险

### ISSUE THREAD

**Issue by OneHangH** [yz1311/rn-umeng-module#5]
![image](https://user-images.githubusercontent.com/31791685/133712043-a90d7749-9f95-4b7b-b8a6-c1f8a91e3e5f.png)

**Comment by yz1311** [comment]
这个库已经根据官方的api适配过隐私合规了，原生调用preInit，在用户同意协议之后才在js端调用init，我用的时候也通过的审核比较严格的应用宝
不过既然sdk更新了，我有空升级下

**Comment by OneHangH** [comment]
嗯嗯，因为我这边也是今天看到友盟官网弹窗提醒让升级到最新sdk，更新了采集字段和访问权限的隐私保护升级。辛苦大佬了
![image](https://user-images.githubusercontent.com/31791685/133715726-db3d1aa0-75ba-4d7b-8e62-977760a20e4f.png)
